version: "3.9"

services:
  python-script:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./python-script:/app
      - ./memes:/memes
    environment:
      - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/...
      - IMAGE_DIRECTORY=/memes

  file-server:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./memes:/usr/share/nginx/html
